# Generated by Django 4.1.7 on 2023-03-12 16:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("1", "Директор"),
                            ("2", "Зам. директора"),
                            ("3", "Начальник відділу"),
                            ("4", "Зам. начальника відділу"),
                            ("5", "Старший менеджер"),
                            ("6", "Менеджер"),
                            ("7", "Офісний працівник"),
                        ],
                        max_length=1,
                    ),
                ),
                ("date_of_employment", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
